# Generated by Django 6.1 on 2026-08-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_enrollment"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="students/"),
        ),
    ]
